### ISSUE TITLE
Bewertungssystem für die Vorschläge für die Spezifikation der zuzuliefernden Metadaten

### ISSUE THREAD

**Issue by kwenzig** [paneldata/data-specification#1]
1. SOEP macht einen Vorschlag und assignt für jede kooperierende Institution standardmäßig einen Account. Jede Institution kann aber auch mit einem anderen Account an der Abstimmung teilnehmen.
2. Nach Prüfung vergibt der:die Beauftragte einer Institution ein vorbereitetes Label, z.B. SOEP:NO und pairfam:YES. Wenn mit YES gevotet wird, kann das eigene Assignment entfernt werden. (GitHub loggt die Label-Vergabe für alle sichtbar mit.)
3. Rückfragen, Diskussionsbeiträge und Alternativvorschläge können als Kommentar angefügt werden.
4. Ziel ist, dass über den Gegenstand des Vorschlags zügig ein Konsens hergestellt wird.
5. Final abgestimmte Issues bekommen das Label APPROVED bzw. REJECTED und werden gelockt.

**Comment by ukrieger** [comment]
Du schreibst jetzt hier Verfahrensvorschläge, oder? Mir ist an einem solchen automatisierten Prozess sehr gelegen. Wichtig wäre mit eine Format-Vorgabe, die dann möglichst langfristig stabil bleibt. Und in meiner Naivität würde ich jetzt meinen, das diese Vorgabe durch das System bestimmt ist?

**Comment by kwenzig** [comment]
Jupp. Und mit diesem Verfahren wollen wir zu einem solchen automatisierten Prozess kommen. Das System, das sind wir. :-)
