### ISSUE TITLE
CSV-Dateien müssen genau die erforderlichen Spalten in der spezifizierten Reihenfolge enthalten

### ISSUE THREAD

**Issue by kwenzig** [paneldata/data-specification#2]
Wir wollen künftig ein automatisches Feedback zu den gelieferten Metadaten geben. Wenn wir [frictionlessdata.io](http://frictionlessdata.io) verwenden, um diese Tests durchzuführen, dürfen nur die erforderlichen Spalten geliefert werden. (Die Reihenfolge ist bleibt irrelevant.)

**Comment by afuetterer** [comment]
Die Reihenfolge kann ignoriert werden. Die Spaltennamen und Anzahl ist aber relevant.
